### ISSUE TITLE
大佬，发送消息类文档中是否可以补全一下通过类的消息结构？

### ISSUE THREAD

**Issue by mumutoy** [smallevilbeast/wechat_pc_api#4]
showdoc文档中提到接受好友申请、转账、加群等消息之后，都可以回复通过
但是文档内只是提到了，发送给对应接口或者设置自动接受，但是并没有对应的回复数据结构
不知道是否能够补全这部分的说明。

感谢大佬提供这么棒的产品。

**Comment by smallevilbeast** [comment]
直接接收

**Comment by smallevilbeast** [comment]
只有接收功能
