### ISSUE TITLE
能接受到小程序消息，但怎么发送小程序消息呢？

### ISSUE THREAD

**Issue by aileone** [smallevilbeast/wechat_pc_api#7]
接口中没有发送小程序消息的说明！
需要怎样，才能将受到的小程序消息转发呢？
忘指教！
谢谢
试过将小程序中的xml中URL通过发送“链接消息”的方式发出去，能发出去，但是消息无法链接到小程序！

**Comment by zhang8929** [comment]
这个问题解决了吗?

**Comment by zhang8929** [comment]
> 接口中没有发送小程序消息的说明！
> 需要怎样，才能将受到的小程序消息转发呢？
> 忘指教！
> 谢谢
> 试过将小程序中的xml中URL通过发送“链接消息”的方式发出去，能发出去，但是消息无法链接到小程序！

这个问题解决了吗?
